apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-rescue-backend
spec:
  selector:
    matchLabels:
      app: animal-rescue-backend
  template:
    metadata:
      labels:
        app: animal-rescue-backend
    spec:
      containers:
        - name: animal-rescue-backend
          image: andriykalashnykov/animal-rescue-backend:latest
#          image: springcloudservices/animal-rescue-backend:latest
          env:
            - name: FRONTEND_URI
              value: "http://animal-rescue-frontend.animal-rescue.svc.cluster.local/rescue"
#            - name: spring.profiles.active
#              value: k8s
#            - name: spring.security.oauth2.resourceserver.jwt.jwk-set-uri
#              valueFrom:
#                secretKeyRef:
#                  name: sso-credentials
#                  key: jwk-set-uri
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: animal-rescue-backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: animal-rescue-backend
