management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*,wavefront"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true

wavefront:
  freemium-account: true
  application:
    name: animal-rescue
    service: backend

logging.level:
  org.springframework: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://any.uaa.uri/token_keys