management:
  endpoint:
    info:
      enabled: true
    loggers:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*,wavefront"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
#    export:
#      wavefront:
#        api-token: "531424c6-bc68-49e7-ada7-92cd12149957"
#        uri: "https://wavefront.surf"

# https://wavefront.surf/us/DhHT9951jD

wavefront:
  freemium-account: true
  application:
    name: animal-rescue
    service: backend

logging:
  pattern:
    console: "%clr(%d{YYYY-MM-dd E HH:mm:ss.SSS}){faint} %clr([traceid=%X{traceId:-} spanid=%X{spanId:-} parentspanid=%X{parentId:-}]){faint} %clr(%-5p) %clr(${PID}){faint} %clr([%8.15t]){faint} %clr(%c{1.}:%L){cyan} %clr(:){red} %clr(%m){faint}%n"
  level:
    ROOT: "INFO"
    org.springframework: "INFO"
    web.servlet.DispatcherServlet: "DEBUG"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://any.uaa.uri/token_keys
  output:
    ansi:
      enabled: always