management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    console: "%clr(%d{YYYY-MM-dd E HH:mm:ss.SSS}){faint} %clr(%-5p) %clr(${PID}){faint} %clr([%8.15t]){faint} %clr(%c{1.}:%L){cyan} %clr(:){red} %clr(%m){faint}%n"
  level:
    ROOT: "INFO"
    org.springframework: "INFO"
    web.servlet.DispatcherServlet: "DEBUG"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://any.uaa.uri/token_keys
  output:
    ansi:
      enabled: always