name: Test All

on:
  push:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Setup Java JDK
      uses: actions/setup-java@v2.3.1
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Run tests
      run: ./scripts/local.sh backend

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.17.6

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Install dependencies
        run: ./scripts/local.sh init

      - name: Run tests
        run: |
          ./scripts/local.sh start --quiet
          ./scripts/local.sh e2e --quiet
          ./scripts/local.sh stop

  frontend-e2e-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.17.6

      - name: Install dependencies
        run: ./scripts/local.sh init

      - name: Run Frontend ESLint
        run: |
          cd frontend
          npm run lint

      - name: Run E2E ESLint
        run: |
          cd e2e
          npm run lint

  publish:
    runs-on: ubuntu-latest
    needs: [ backend-test, e2e-test, frontend-e2e-lint ]
    if: |
      github.ref == 'refs/heads/main' &&
      needs.backend-test.result == 'success' &&
      needs.e2e-test.result == 'success' &&
      needs.frontend-e2e-lint.result == 'success'
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/animal-rescue-backend
          path: backend
          builder: gcr.io/paketo-buildpacks/builder:base
      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/animal-rescue-backend:latest

      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.17.6

      - name: Assemble frontend
        run: |
          ./scripts/local.sh init
          ./gradlew :frontend:assemble
#      - name:  Build frontend image
#        uses: docker/build-push-action@v2.7.0
#        with:
#          context: frontend
#          file:  frontend/Dockerfile
#          platforms: linux/amd64
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/animal-rescue-frontend:latest
#          cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/animal-rescue-frontend-cache:latest
#          cache-to: ${{ secrets.DOCKERHUB_USERNAME }}/danimal-rescue-frontend-cache:latest
#      - name: Build frontend image
#        uses: mamezou-tech/buildpacks-action@master
#        with:
#          image: ${{ secrets.DOCKERHUB_USERNAME }}/animal-rescue-frontend
#          path: frontend
#          builder: gcr.io/paketo-buildpacks/builder:base
#          env: "BP_NODE_RUN_SCRIPTS=build BP_NODE_VERSION=14.17.6"
#      - name: Push frontend image
#        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/animal-rescue-frontend:latest


