name: Test All

on: [push]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup Java JDK
      uses: actions/setup-java@v2.3.0
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Run tests
      run: ./scripts/local.sh backend

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.17.6

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Install dependencies
        run: ./scripts/local.sh init

      - name: Run tests
        run: |
          ./scripts/local.sh start --quiet
          ./scripts/local.sh e2e --quiet
          ./scripts/local.sh stop

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.17.6

      - name: Install dependencies
        run: ./scripts/local.sh init

      - name: Run Frontend ESLint
        run: |
          cd frontend
          npm run lint

      - name: Run E2E ESLint
        run: |
          cd e2e
          npm run lint

  publish:
    runs-on: ubuntu-latest
    needs: [ backend-test, e2e-test, lint ]
    if: |
      github.ref == 'refs/heads/main' &&
      needs.backend-test.result == 'success' &&
      needs.e2e-test.result == 'success' &&
      needs.lint.result == 'success'
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Build backend image
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/animal-rescue-backend
          path: backend
          builder: gcr.io/paketo-buildpacks/builder:base
      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/animal-rescue-backend:latest

      - name: Setup Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.17.6

      - name: Assemble frontend
        run: |
          ./scripts/local.sh init
          ./gradlew :frontend:assemble
      - name: Build frontend image
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/animal-rescue-frontend
          path: frontend
          builder: gcr.io/paketo-buildpacks/builder:base
          env: "BP_NODE_RUN_SCRIPTS=build BP_NODE_VERSION=14.17.6"
      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/animal-rescue-frontend:latest


